#! /usr/bin/env node

var exec = require('child_process').exec,
    fs = require('fs');

const MODULE_INFO = (function (manifest) {
    return {
        VERSION: manifest.match(/version: ([\S]+)/m)[1],
        NAME: manifest.match(/name: ([\S]+)/m)[1]
    };
}(fs.readFileSync('manifest').toString()));

const DEST_FOLDER  = 'modules/commonjs/' + MODULE_INFO.NAME + '/' + MODULE_INFO.VERSION;
const TI_MODULE_XML = '<?xml version="1.0" encoding="UTF-8"?><ti:module xmlns:ti="http://ti.appcelerator.org" xmlns:android="http://schemas.android.com/apk/res/android"></ti:module>'

var Slave = (function() {
    var tasks = [],
        currentTask = 0,
        instance = {};

    instance.doThis = function register(task) {
        tasks.push(task);
        return instance;
    };

    instance.andDoThat = instance.doThis;
    
    instance.execute = function execute(done) {
        currentTask = currentTask || 0;
            
        if (!tasks[currentTask]) { return done(); }

        exec(tasks[currentTask], function (err) {
            if (err) { return done(err); }
            ++currentTask;
            execute(done);
        });
    }

    return instance;
}());

console.log(MODULE_INFO.NAME, "v" + MODULE_INFO.VERSION);
Slave
    .doThis('mv ' + MODULE_INFO.NAME + '.js __save')
    .andDoThat('browserify -s ' + MODULE_INFO.NAME + ' -o __temp.js __save')
    .andDoThat('uglify -s __temp.js -o ' + MODULE_INFO.NAME +'.js')
    .andDoThat('echo \'' + TI_MODULE_XML + '\' > timodule.xml')
    .andDoThat('mkdir -p ' + DEST_FOLDER + ' && cp manifest timodule.xml ' + MODULE_INFO.NAME + '.js ' + DEST_FOLDER)
    .andDoThat('zip -r ' + MODULE_INFO.NAME + '-commonjs-' + MODULE_INFO.VERSION + '.zip ' + DEST_FOLDER)
    .andDoThat('rm -r modules __temp.js timodule.xml && mv __save ' + MODULE_INFO.NAME + '.js')
    .execute(function (err) { console.log(err || "Build Successful!"); });

